plugins:
  nephio-project:
    plugins:
    - approve
    - assign
    - blunderbuss
    - help
    - heart
    - hold
    - invalidcommitmsg
    - label
    - lgtm
    - trigger
    - verify-owners
    - wip
  nephio-project/test-infra:
    plugins:
    - config-updater

external_plugins:
  nephio-project:
  - name: needs-rebase
    events:
      - issue_comment
      - pull_request

config_updater:
  maps:
    prow/config/config.yaml:
      name: config
      namespace: prow
    prow/config/plugins.yaml:
      name: plugins
      namespace: prow
